# Generated by Django 5.2.5 on 2025-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0004_suspiciousip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='suspiciousip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
