# Generated by Django 5.2.5 on 2025-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0005_alter_requestlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
