[project]
name = "alx-backend-security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.5",
    "django-ip-geolocation>=1.6.1",
    "hiredis>=3.2.1",
    "redis>=6.4.0",
    "requests>=2.32.5",
]
